export default {
  home: '首页',
  about: '关于我们',
  action: '现在行动',
  links: '相关文件',
  donation: '现在捐款',
  logoText: '喵之家',
  bannerTitle: '欢迎来到喵之家',
  bannerSubtitle: '义工服务一直以来是推动我们动物协会达成使命的重要角色。 Purrifichome欢迎和感谢充满爱心与热情的您想要加入我们的行列！',
  bannerSubtitleHelpText: '义工角色分很多种，如果你有其他特长，也欢迎加入猫之家的队伍。',
  whatWeDo: '我们的使命',
  service1: '中文或者英文写作',
  service1Desc: '帮助我们推广寄养领养平台, 科学喂养理念。',
  service2: 'Front line救助和运输',
  service2Desc: '第一线救助人员，帮忙做food drive或接送捐赠品和猫咪。',
  service3: '寄养',
  service3Desc: '寄养家庭 (短期或长期)，帮忙转发寄养领养资讯。',
  allOtherHelps: '帮忙转发寄养领养资讯、群内分享或帮忙解答关于猫咪一切知识、冬天帮忙制作和放置猫窝、帮忙喂养和观察流浪猫。',
  kittyText: '让我们伸出善意的手，给它们爱与温暖。',
};
